services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:9000"
    networks:
      - net
    depends_on:
      - db
    environment:
      - DATABASE_TARGET=postgres
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

networks:
  net:
    driver: bridge

volumes:
  data:
